apiVersion: batch/v1
kind: Job
metadata:
  name: chssgme-job
spec:
  template:
    spec:
      containers:
      - name: chssgme-job
        image: yash5090/chssgme:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
